name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: BSFishy/pip-action@v1
        with:
          requirements: ./.github/workflows/requirements.txt
      - run: python ./build.py
        working-directory: ./.github/workflows
